### ISSUE TITLE
Shape for circular reference

### ISSUE THREAD

**Issue by yhack** [shexSpec/spec#24]
In ShEx it doesn't seem possible to define a shape expression for a circular reference in data. For example, consider the following data about people and dogs:

```
Bob owns Fido
Fido likes Jane
Jane owns Spot
Spot likes Jane
```

I could define a shape for a person who owns a dog that likes a person. However it doesn't seem possible to define a shape for a person who owns dog that likes them. In the example, this would include Jane but not Bob. I'm new to ShEx; maybe I'm missing something. Is there any way for ShEx to define these shapes?

**Comment by labra** [comment]
ShEx has no problem defining recursive shapes with circular references. 
If I understand correctly want you meant, a possible solution could be:

```
PREFIX :       <http://example.org/>

:Person { 
 :owns  @:Dog;
}

:Dog {
  :likes @:Person
}
```

where the RDF data could be represented as:

```
@prefix :      <http://example.org/> .

:Bob    :owns   :Fido .
:Jane   :owns   :Spot .
:Fido   :likes  :Jane .
:Spot   :likes  :Jane .
```

You can play with that example [here](https://goo.gl/jY1dzX).

You can also read more information about how ShEx handles recursive shapes in section 4.7.2 of [the validating RDF data book](http://book.validatingrdf.com/bookHtml010.html#sec81).

**Comment by yhack** [comment]
@labra thank you for putting that example together and sharing the book. Both are helpful. The schema you shared is recursive, circular if you will, but it doesn't distinguish between circular and non-circular relationships in the data. 

Jane's circular relationship with Spot might be graphed like this:
```
  ┌──── owns ────↴
Jane            Spot
  └──── likes ───┘
```
Bob, on the other hand, does not have a circular relationship with his dog:
```
Bob ──── owns ──── Fido ──── likes ──── Jane
```

In your schema, Person must own a Dog, and Dog must like a Person. This is true of both Jane and Bob. Indeed, the example you linked evaluated both Jane and Bob as valid. What I want to model is the circular relationship of PersonWhoOwnsADogThatLikesThisPerson. This should be valid for Jane but not Bob, because whilst Bob's dog likes a person, it's not him.

**Comment by labra** [comment]
OK, now I understand what you wanted to express. As far as I know it is not possible right now. A possible syntax could be:

```turtle
PREFIX :       <http://example.org/>

:Person { 
 $<Dog> :owns  @:Dog;
$this = $<Dog>/likes
}

:Dog {
  :likes @:Person
}
```

but this is not yet supported by ShEx 2.0. 

We are planning to extend ShEx with a feature that allows arithmetic and comparison operators to ShEx and with that extension this use case could also be solved. That extension was recorded in [this issue](https://github.com/shexSpec/shex/issues/24). 

We usually record issues in the `shex` repository instead of this one, so I will add a issue for this use case there and if you agree, you can close this one.

**Comment by yhack** [comment]
Got it, thanks. The syntax you propose looks like it would work. Ideally it would work with larger loops too like `A -> B -> C -> A`. I'll go ahead and close this ticket.
