### ISSUE TITLE
ShExC [50] exclusion missing '.'

### ISSUE THREAD

**Issue by blake-regalia** [shexSpec/spec#35]
In ShExC [49] the language says `If "." matches and exclusion matches ...` , but none of the productions include a full stop token.

@ericprud says:
> exclusion should include a '.' a al:
> [50]       exclusion       ::=       '.' '-' (iri | literal | LANGTAG) '~'?

**Comment by ericprud** [comment]
updated in http://shex.io/shex-semantics/index.html#prod-exclusion
and https://shexspec.github.io/spec/#prod-exclusion
```
[50] | exclusion | ::= | '.' '-' (iri \| literal \| LANGTAG) '~'?
```
