### ISSUE TITLE
ShExC importDecl inconsistent with example

### ISSUE THREAD

**Issue by gkellogg** [shexSpec/spec#41]
As noted in https://lists.w3.org/Archives/Public/public-shex/2021Aug/0000.html.

The ShExC grammar for importDecl is single-valued, but _IMPORT EXAMPLE 2 - CIRCULAR IMPORT_ is multi-valued. Presumably, the example should use two separate IMPORT statements.

**Comment by ericprud** [comment]
Looks like https://github.com/shexSpec/spec/blob/gh-pages/scripts.js#L77 was catching the error but i was failing to look in the console. Maybe i should change the background color if there are errors to make sure I notice (or do more github actions work).
