### ISSUE TITLE
ObjectLiteral type attribute

### ISSUE THREAD

**Issue by ektrah** [shexSpec/spec#54]
[Section 2.1](https://shexspec.github.io/spec/#json-grammar) currently says:

> ShEx data structures are represented as JSON objects with a member with the name "type" (i.e. an object with a type attribute):
>
>     { "type": "typeName", member0…n }
>         ↑

And [Section 5.4](https://shexspec.github.io/spec/#node-constraints) defines:

>     ObjectLiteral { value:STRING language:STRING? type:STRING? }
>                                                    ↑

Is there a conflict between `type` and `type`?

**Comment by ericprud** [comment]
Hmm, Yes and no. The JSG in the spec spares the reader of some details. Some readers, however, pay attention to details (looking your direction). The JSG that I use for testing has a directive that [disables the type expectation for ObjectLiteral](https://github.com/shexSpec/shexTest/blob/main/doc/ShExJ.jsg#L11):
```
.TYPE type - ObjectLiteral
```
(The meaning is: expect the production name (e.g. `Schema`, `ShapeDecl`, `ShapeOr`, …) as `type` everywhere except those productions referenced after the `-`. Maybe there's a clearer name for `.TYPE`; maybe `.PRODNAME`? JSG can still change.)

So now the Q is do I
1. mention that directive, or at least it effect, in §2.1?
2. write a spec for [jsg](https://github.com/ericprud/jsg) and reference it from the grammar?
3. do nothing, assuming I've already communicated with the only person in the world who'll notice?

**Comment by ektrah** [comment]
Thanks for the confirmation. I think a brief note  on this exception in §2.1 would be quite helpful.

**Comment by ericprud** [comment]
First commit above was on the wrong branch. Second produces the note at the bottom of the [editor's draft](https://shexspec.github.io/spec/#json-grammar).

Feel free to close this issue if you feel it's address.

Most of all, thanks for improving the spec!

**Comment by ericprud** [comment]
for posterity, markup errors fix in 8343717
c.f. https://github.com/shexSpec/spec/runs/7948878949?check_suite_focus=true
